/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as SlideTrustRouteImport } from './routes/slide-trust'
import { Route as SlideTimelineRouteImport } from './routes/slide-timeline'
import { Route as SlideSharingRouteImport } from './routes/slide-sharing'
import { Route as SlideServicesRouteImport } from './routes/slide-services'
import { Route as SlideRelationshipRouteImport } from './routes/slide-relationship'
import { Route as SlideRegulationRouteImport } from './routes/slide-regulation'
import { Route as SlideProductsRouteImport } from './routes/slide-products'
import { Route as SlidePhysicalDigitalRouteImport } from './routes/slide-physical-digital'
import { Route as SlidePartnershipsRouteImport } from './routes/slide-partnerships'
import { Route as SlideOpportunityRouteImport } from './routes/slide-opportunity'
import { Route as SlideLifetimeRouteImport } from './routes/slide-lifetime'
import { Route as SlideJourneyRouteImport } from './routes/slide-journey'
import { Route as SlideHeroClosingRouteImport } from './routes/slide-hero-closing'
import { Route as SlideFlywheelRouteImport } from './routes/slide-flywheel'
import { Route as SlideFinalRouteImport } from './routes/slide-final'
import { Route as SlideEuropeRouteImport } from './routes/slide-europe'
import { Route as SlideEcosystemRouteImport } from './routes/slide-ecosystem'
import { Route as SlideDataRouteImport } from './routes/slide-data'
import { Route as SlideContextRouteImport } from './routes/slide-context'
import { Route as SlideContactRouteImport } from './routes/slide-contact'
import { Route as SlideCapabilitiesRouteImport } from './routes/slide-capabilities'
import { Route as SlideBusinessModelRouteImport } from './routes/slide-business-model'
import { Route as SlideAiRouteImport } from './routes/slide-ai'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PrintRouteImport } from './routes/print'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MarketRouteImport } from './routes/market'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideTrustRoute = SlideTrustRouteImport.update({
  id: '/slide-trust',
  path: '/slide-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideTimelineRoute = SlideTimelineRouteImport.update({
  id: '/slide-timeline',
  path: '/slide-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideSharingRoute = SlideSharingRouteImport.update({
  id: '/slide-sharing',
  path: '/slide-sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideServicesRoute = SlideServicesRouteImport.update({
  id: '/slide-services',
  path: '/slide-services',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideRelationshipRoute = SlideRelationshipRouteImport.update({
  id: '/slide-relationship',
  path: '/slide-relationship',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideRegulationRoute = SlideRegulationRouteImport.update({
  id: '/slide-regulation',
  path: '/slide-regulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideProductsRoute = SlideProductsRouteImport.update({
  id: '/slide-products',
  path: '/slide-products',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidePhysicalDigitalRoute = SlidePhysicalDigitalRouteImport.update({
  id: '/slide-physical-digital',
  path: '/slide-physical-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidePartnershipsRoute = SlidePartnershipsRouteImport.update({
  id: '/slide-partnerships',
  path: '/slide-partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideOpportunityRoute = SlideOpportunityRouteImport.update({
  id: '/slide-opportunity',
  path: '/slide-opportunity',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideLifetimeRoute = SlideLifetimeRouteImport.update({
  id: '/slide-lifetime',
  path: '/slide-lifetime',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideJourneyRoute = SlideJourneyRouteImport.update({
  id: '/slide-journey',
  path: '/slide-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideHeroClosingRoute = SlideHeroClosingRouteImport.update({
  id: '/slide-hero-closing',
  path: '/slide-hero-closing',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideFlywheelRoute = SlideFlywheelRouteImport.update({
  id: '/slide-flywheel',
  path: '/slide-flywheel',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideFinalRoute = SlideFinalRouteImport.update({
  id: '/slide-final',
  path: '/slide-final',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideEuropeRoute = SlideEuropeRouteImport.update({
  id: '/slide-europe',
  path: '/slide-europe',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideEcosystemRoute = SlideEcosystemRouteImport.update({
  id: '/slide-ecosystem',
  path: '/slide-ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideDataRoute = SlideDataRouteImport.update({
  id: '/slide-data',
  path: '/slide-data',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideContextRoute = SlideContextRouteImport.update({
  id: '/slide-context',
  path: '/slide-context',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideContactRoute = SlideContactRouteImport.update({
  id: '/slide-contact',
  path: '/slide-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideCapabilitiesRoute = SlideCapabilitiesRouteImport.update({
  id: '/slide-capabilities',
  path: '/slide-capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideBusinessModelRoute = SlideBusinessModelRouteImport.update({
  id: '/slide-business-model',
  path: '/slide-business-model',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideAiRoute = SlideAiRouteImport.update({
  id: '/slide-ai',
  path: '/slide-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/market': typeof MarketRoute
  '/pricing': typeof PricingRoute
  '/print': typeof PrintRoute
  '/product': typeof ProductRoute
  '/slide-ai': typeof SlideAiRoute
  '/slide-business-model': typeof SlideBusinessModelRoute
  '/slide-capabilities': typeof SlideCapabilitiesRoute
  '/slide-contact': typeof SlideContactRoute
  '/slide-context': typeof SlideContextRoute
  '/slide-data': typeof SlideDataRoute
  '/slide-ecosystem': typeof SlideEcosystemRoute
  '/slide-europe': typeof SlideEuropeRoute
  '/slide-final': typeof SlideFinalRoute
  '/slide-flywheel': typeof SlideFlywheelRoute
  '/slide-hero-closing': typeof SlideHeroClosingRoute
  '/slide-journey': typeof SlideJourneyRoute
  '/slide-lifetime': typeof SlideLifetimeRoute
  '/slide-opportunity': typeof SlideOpportunityRoute
  '/slide-partnerships': typeof SlidePartnershipsRoute
  '/slide-physical-digital': typeof SlidePhysicalDigitalRoute
  '/slide-products': typeof SlideProductsRoute
  '/slide-regulation': typeof SlideRegulationRoute
  '/slide-relationship': typeof SlideRelationshipRoute
  '/slide-services': typeof SlideServicesRoute
  '/slide-sharing': typeof SlideSharingRoute
  '/slide-timeline': typeof SlideTimelineRoute
  '/slide-trust': typeof SlideTrustRoute
  '/vision': typeof VisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/market': typeof MarketRoute
  '/pricing': typeof PricingRoute
  '/print': typeof PrintRoute
  '/product': typeof ProductRoute
  '/slide-ai': typeof SlideAiRoute
  '/slide-business-model': typeof SlideBusinessModelRoute
  '/slide-capabilities': typeof SlideCapabilitiesRoute
  '/slide-contact': typeof SlideContactRoute
  '/slide-context': typeof SlideContextRoute
  '/slide-data': typeof SlideDataRoute
  '/slide-ecosystem': typeof SlideEcosystemRoute
  '/slide-europe': typeof SlideEuropeRoute
  '/slide-final': typeof SlideFinalRoute
  '/slide-flywheel': typeof SlideFlywheelRoute
  '/slide-hero-closing': typeof SlideHeroClosingRoute
  '/slide-journey': typeof SlideJourneyRoute
  '/slide-lifetime': typeof SlideLifetimeRoute
  '/slide-opportunity': typeof SlideOpportunityRoute
  '/slide-partnerships': typeof SlidePartnershipsRoute
  '/slide-physical-digital': typeof SlidePhysicalDigitalRoute
  '/slide-products': typeof SlideProductsRoute
  '/slide-regulation': typeof SlideRegulationRoute
  '/slide-relationship': typeof SlideRelationshipRoute
  '/slide-services': typeof SlideServicesRoute
  '/slide-sharing': typeof SlideSharingRoute
  '/slide-timeline': typeof SlideTimelineRoute
  '/slide-trust': typeof SlideTrustRoute
  '/vision': typeof VisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/market': typeof MarketRoute
  '/pricing': typeof PricingRoute
  '/print': typeof PrintRoute
  '/product': typeof ProductRoute
  '/slide-ai': typeof SlideAiRoute
  '/slide-business-model': typeof SlideBusinessModelRoute
  '/slide-capabilities': typeof SlideCapabilitiesRoute
  '/slide-contact': typeof SlideContactRoute
  '/slide-context': typeof SlideContextRoute
  '/slide-data': typeof SlideDataRoute
  '/slide-ecosystem': typeof SlideEcosystemRoute
  '/slide-europe': typeof SlideEuropeRoute
  '/slide-final': typeof SlideFinalRoute
  '/slide-flywheel': typeof SlideFlywheelRoute
  '/slide-hero-closing': typeof SlideHeroClosingRoute
  '/slide-journey': typeof SlideJourneyRoute
  '/slide-lifetime': typeof SlideLifetimeRoute
  '/slide-opportunity': typeof SlideOpportunityRoute
  '/slide-partnerships': typeof SlidePartnershipsRoute
  '/slide-physical-digital': typeof SlidePhysicalDigitalRoute
  '/slide-products': typeof SlideProductsRoute
  '/slide-regulation': typeof SlideRegulationRoute
  '/slide-relationship': typeof SlideRelationshipRoute
  '/slide-services': typeof SlideServicesRoute
  '/slide-sharing': typeof SlideSharingRoute
  '/slide-timeline': typeof SlideTimelineRoute
  '/slide-trust': typeof SlideTrustRoute
  '/vision': typeof VisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/b2b'
    | '/market'
    | '/pricing'
    | '/print'
    | '/product'
    | '/slide-ai'
    | '/slide-business-model'
    | '/slide-capabilities'
    | '/slide-contact'
    | '/slide-context'
    | '/slide-data'
    | '/slide-ecosystem'
    | '/slide-europe'
    | '/slide-final'
    | '/slide-flywheel'
    | '/slide-hero-closing'
    | '/slide-journey'
    | '/slide-lifetime'
    | '/slide-opportunity'
    | '/slide-partnerships'
    | '/slide-physical-digital'
    | '/slide-products'
    | '/slide-regulation'
    | '/slide-relationship'
    | '/slide-services'
    | '/slide-sharing'
    | '/slide-timeline'
    | '/slide-trust'
    | '/vision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/b2b'
    | '/market'
    | '/pricing'
    | '/print'
    | '/product'
    | '/slide-ai'
    | '/slide-business-model'
    | '/slide-capabilities'
    | '/slide-contact'
    | '/slide-context'
    | '/slide-data'
    | '/slide-ecosystem'
    | '/slide-europe'
    | '/slide-final'
    | '/slide-flywheel'
    | '/slide-hero-closing'
    | '/slide-journey'
    | '/slide-lifetime'
    | '/slide-opportunity'
    | '/slide-partnerships'
    | '/slide-physical-digital'
    | '/slide-products'
    | '/slide-regulation'
    | '/slide-relationship'
    | '/slide-services'
    | '/slide-sharing'
    | '/slide-timeline'
    | '/slide-trust'
    | '/vision'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/b2b'
    | '/market'
    | '/pricing'
    | '/print'
    | '/product'
    | '/slide-ai'
    | '/slide-business-model'
    | '/slide-capabilities'
    | '/slide-contact'
    | '/slide-context'
    | '/slide-data'
    | '/slide-ecosystem'
    | '/slide-europe'
    | '/slide-final'
    | '/slide-flywheel'
    | '/slide-hero-closing'
    | '/slide-journey'
    | '/slide-lifetime'
    | '/slide-opportunity'
    | '/slide-partnerships'
    | '/slide-physical-digital'
    | '/slide-products'
    | '/slide-regulation'
    | '/slide-relationship'
    | '/slide-services'
    | '/slide-sharing'
    | '/slide-timeline'
    | '/slide-trust'
    | '/vision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  B2bRoute: typeof B2bRoute
  MarketRoute: typeof MarketRoute
  PricingRoute: typeof PricingRoute
  PrintRoute: typeof PrintRoute
  ProductRoute: typeof ProductRoute
  SlideAiRoute: typeof SlideAiRoute
  SlideBusinessModelRoute: typeof SlideBusinessModelRoute
  SlideCapabilitiesRoute: typeof SlideCapabilitiesRoute
  SlideContactRoute: typeof SlideContactRoute
  SlideContextRoute: typeof SlideContextRoute
  SlideDataRoute: typeof SlideDataRoute
  SlideEcosystemRoute: typeof SlideEcosystemRoute
  SlideEuropeRoute: typeof SlideEuropeRoute
  SlideFinalRoute: typeof SlideFinalRoute
  SlideFlywheelRoute: typeof SlideFlywheelRoute
  SlideHeroClosingRoute: typeof SlideHeroClosingRoute
  SlideJourneyRoute: typeof SlideJourneyRoute
  SlideLifetimeRoute: typeof SlideLifetimeRoute
  SlideOpportunityRoute: typeof SlideOpportunityRoute
  SlidePartnershipsRoute: typeof SlidePartnershipsRoute
  SlidePhysicalDigitalRoute: typeof SlidePhysicalDigitalRoute
  SlideProductsRoute: typeof SlideProductsRoute
  SlideRegulationRoute: typeof SlideRegulationRoute
  SlideRelationshipRoute: typeof SlideRelationshipRoute
  SlideServicesRoute: typeof SlideServicesRoute
  SlideSharingRoute: typeof SlideSharingRoute
  SlideTimelineRoute: typeof SlideTimelineRoute
  SlideTrustRoute: typeof SlideTrustRoute
  VisionRoute: typeof VisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-trust': {
      id: '/slide-trust'
      path: '/slide-trust'
      fullPath: '/slide-trust'
      preLoaderRoute: typeof SlideTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-timeline': {
      id: '/slide-timeline'
      path: '/slide-timeline'
      fullPath: '/slide-timeline'
      preLoaderRoute: typeof SlideTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-sharing': {
      id: '/slide-sharing'
      path: '/slide-sharing'
      fullPath: '/slide-sharing'
      preLoaderRoute: typeof SlideSharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-services': {
      id: '/slide-services'
      path: '/slide-services'
      fullPath: '/slide-services'
      preLoaderRoute: typeof SlideServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-relationship': {
      id: '/slide-relationship'
      path: '/slide-relationship'
      fullPath: '/slide-relationship'
      preLoaderRoute: typeof SlideRelationshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-regulation': {
      id: '/slide-regulation'
      path: '/slide-regulation'
      fullPath: '/slide-regulation'
      preLoaderRoute: typeof SlideRegulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-products': {
      id: '/slide-products'
      path: '/slide-products'
      fullPath: '/slide-products'
      preLoaderRoute: typeof SlideProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-physical-digital': {
      id: '/slide-physical-digital'
      path: '/slide-physical-digital'
      fullPath: '/slide-physical-digital'
      preLoaderRoute: typeof SlidePhysicalDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-partnerships': {
      id: '/slide-partnerships'
      path: '/slide-partnerships'
      fullPath: '/slide-partnerships'
      preLoaderRoute: typeof SlidePartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-opportunity': {
      id: '/slide-opportunity'
      path: '/slide-opportunity'
      fullPath: '/slide-opportunity'
      preLoaderRoute: typeof SlideOpportunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-lifetime': {
      id: '/slide-lifetime'
      path: '/slide-lifetime'
      fullPath: '/slide-lifetime'
      preLoaderRoute: typeof SlideLifetimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-journey': {
      id: '/slide-journey'
      path: '/slide-journey'
      fullPath: '/slide-journey'
      preLoaderRoute: typeof SlideJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-hero-closing': {
      id: '/slide-hero-closing'
      path: '/slide-hero-closing'
      fullPath: '/slide-hero-closing'
      preLoaderRoute: typeof SlideHeroClosingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-flywheel': {
      id: '/slide-flywheel'
      path: '/slide-flywheel'
      fullPath: '/slide-flywheel'
      preLoaderRoute: typeof SlideFlywheelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-final': {
      id: '/slide-final'
      path: '/slide-final'
      fullPath: '/slide-final'
      preLoaderRoute: typeof SlideFinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-europe': {
      id: '/slide-europe'
      path: '/slide-europe'
      fullPath: '/slide-europe'
      preLoaderRoute: typeof SlideEuropeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-ecosystem': {
      id: '/slide-ecosystem'
      path: '/slide-ecosystem'
      fullPath: '/slide-ecosystem'
      preLoaderRoute: typeof SlideEcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-data': {
      id: '/slide-data'
      path: '/slide-data'
      fullPath: '/slide-data'
      preLoaderRoute: typeof SlideDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-context': {
      id: '/slide-context'
      path: '/slide-context'
      fullPath: '/slide-context'
      preLoaderRoute: typeof SlideContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-contact': {
      id: '/slide-contact'
      path: '/slide-contact'
      fullPath: '/slide-contact'
      preLoaderRoute: typeof SlideContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-capabilities': {
      id: '/slide-capabilities'
      path: '/slide-capabilities'
      fullPath: '/slide-capabilities'
      preLoaderRoute: typeof SlideCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-business-model': {
      id: '/slide-business-model'
      path: '/slide-business-model'
      fullPath: '/slide-business-model'
      preLoaderRoute: typeof SlideBusinessModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-ai': {
      id: '/slide-ai'
      path: '/slide-ai'
      fullPath: '/slide-ai'
      preLoaderRoute: typeof SlideAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  B2bRoute: B2bRoute,
  MarketRoute: MarketRoute,
  PricingRoute: PricingRoute,
  PrintRoute: PrintRoute,
  ProductRoute: ProductRoute,
  SlideAiRoute: SlideAiRoute,
  SlideBusinessModelRoute: SlideBusinessModelRoute,
  SlideCapabilitiesRoute: SlideCapabilitiesRoute,
  SlideContactRoute: SlideContactRoute,
  SlideContextRoute: SlideContextRoute,
  SlideDataRoute: SlideDataRoute,
  SlideEcosystemRoute: SlideEcosystemRoute,
  SlideEuropeRoute: SlideEuropeRoute,
  SlideFinalRoute: SlideFinalRoute,
  SlideFlywheelRoute: SlideFlywheelRoute,
  SlideHeroClosingRoute: SlideHeroClosingRoute,
  SlideJourneyRoute: SlideJourneyRoute,
  SlideLifetimeRoute: SlideLifetimeRoute,
  SlideOpportunityRoute: SlideOpportunityRoute,
  SlidePartnershipsRoute: SlidePartnershipsRoute,
  SlidePhysicalDigitalRoute: SlidePhysicalDigitalRoute,
  SlideProductsRoute: SlideProductsRoute,
  SlideRegulationRoute: SlideRegulationRoute,
  SlideRelationshipRoute: SlideRelationshipRoute,
  SlideServicesRoute: SlideServicesRoute,
  SlideSharingRoute: SlideSharingRoute,
  SlideTimelineRoute: SlideTimelineRoute,
  SlideTrustRoute: SlideTrustRoute,
  VisionRoute: VisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
