/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as SlideTimelineRouteImport } from './routes/slide-timeline'
import { Route as SlideLifetimeRouteImport } from './routes/slide-lifetime'
import { Route as SlideEcosystemRouteImport } from './routes/slide-ecosystem'
import { Route as SlideDataRouteImport } from './routes/slide-data'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PrintRouteImport } from './routes/print'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MarketRouteImport } from './routes/market'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideTimelineRoute = SlideTimelineRouteImport.update({
  id: '/slide-timeline',
  path: '/slide-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideLifetimeRoute = SlideLifetimeRouteImport.update({
  id: '/slide-lifetime',
  path: '/slide-lifetime',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideEcosystemRoute = SlideEcosystemRouteImport.update({
  id: '/slide-ecosystem',
  path: '/slide-ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideDataRoute = SlideDataRouteImport.update({
  id: '/slide-data',
  path: '/slide-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/market': typeof MarketRoute
  '/pricing': typeof PricingRoute
  '/print': typeof PrintRoute
  '/product': typeof ProductRoute
  '/slide-data': typeof SlideDataRoute
  '/slide-ecosystem': typeof SlideEcosystemRoute
  '/slide-lifetime': typeof SlideLifetimeRoute
  '/slide-timeline': typeof SlideTimelineRoute
  '/vision': typeof VisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/market': typeof MarketRoute
  '/pricing': typeof PricingRoute
  '/print': typeof PrintRoute
  '/product': typeof ProductRoute
  '/slide-data': typeof SlideDataRoute
  '/slide-ecosystem': typeof SlideEcosystemRoute
  '/slide-lifetime': typeof SlideLifetimeRoute
  '/slide-timeline': typeof SlideTimelineRoute
  '/vision': typeof VisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/market': typeof MarketRoute
  '/pricing': typeof PricingRoute
  '/print': typeof PrintRoute
  '/product': typeof ProductRoute
  '/slide-data': typeof SlideDataRoute
  '/slide-ecosystem': typeof SlideEcosystemRoute
  '/slide-lifetime': typeof SlideLifetimeRoute
  '/slide-timeline': typeof SlideTimelineRoute
  '/vision': typeof VisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/b2b'
    | '/market'
    | '/pricing'
    | '/print'
    | '/product'
    | '/slide-data'
    | '/slide-ecosystem'
    | '/slide-lifetime'
    | '/slide-timeline'
    | '/vision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/b2b'
    | '/market'
    | '/pricing'
    | '/print'
    | '/product'
    | '/slide-data'
    | '/slide-ecosystem'
    | '/slide-lifetime'
    | '/slide-timeline'
    | '/vision'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/b2b'
    | '/market'
    | '/pricing'
    | '/print'
    | '/product'
    | '/slide-data'
    | '/slide-ecosystem'
    | '/slide-lifetime'
    | '/slide-timeline'
    | '/vision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  B2bRoute: typeof B2bRoute
  MarketRoute: typeof MarketRoute
  PricingRoute: typeof PricingRoute
  PrintRoute: typeof PrintRoute
  ProductRoute: typeof ProductRoute
  SlideDataRoute: typeof SlideDataRoute
  SlideEcosystemRoute: typeof SlideEcosystemRoute
  SlideLifetimeRoute: typeof SlideLifetimeRoute
  SlideTimelineRoute: typeof SlideTimelineRoute
  VisionRoute: typeof VisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-timeline': {
      id: '/slide-timeline'
      path: '/slide-timeline'
      fullPath: '/slide-timeline'
      preLoaderRoute: typeof SlideTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-lifetime': {
      id: '/slide-lifetime'
      path: '/slide-lifetime'
      fullPath: '/slide-lifetime'
      preLoaderRoute: typeof SlideLifetimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-ecosystem': {
      id: '/slide-ecosystem'
      path: '/slide-ecosystem'
      fullPath: '/slide-ecosystem'
      preLoaderRoute: typeof SlideEcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide-data': {
      id: '/slide-data'
      path: '/slide-data'
      fullPath: '/slide-data'
      preLoaderRoute: typeof SlideDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  B2bRoute: B2bRoute,
  MarketRoute: MarketRoute,
  PricingRoute: PricingRoute,
  PrintRoute: PrintRoute,
  ProductRoute: ProductRoute,
  SlideDataRoute: SlideDataRoute,
  SlideEcosystemRoute: SlideEcosystemRoute,
  SlideLifetimeRoute: SlideLifetimeRoute,
  SlideTimelineRoute: SlideTimelineRoute,
  VisionRoute: VisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
